default_platform(:mac)

platform :mac do
  desc "Build and test the AuctionSniper macOS app"
  lane :build do
    sh("cd .. && make generate-no-cache")

    scan(
      workspace: "macOS-AuctionSniper.xcworkspace",
      scheme: "AuctionSniper",
      only_testing: [
        "AuctionSniperUnitTests",
        "AuctionSniperEndToEndTests"
      ],
      clean: true
    )
  end
end